version: '3.8'
services:
    # Web Server Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
        - "8080:80"
        volumes:
            - ./src:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - php
    php:
        container_name: app
        build:
            context: ./docker
            dockerfile: Dockerfile
        environment:
            - APP_ENV=Xplor_test
            - PHP_OPCACHE_ENABLE=1
            - PHP_OPCACHE_ENABLE_CLI=0
            - PHP_OPCACHE_REVALIDATE_FREQ=1
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
        working_dir: /var/www
        volumes:
            - ./src:/var/www
        ports:
            - "9000:9000"